### ISSUE TITLE
Bug: do not generate empty file

### ISSUE THREAD

**Issue by connorjs** [connorjs/css-typed#9]
```txt
apps/web/src/main/global.d.css.ts:3:1
         ✖   3:1  Empty files are not allowed.                                                                      unicorn/no-empty-file
```

Do not generate empty files. Input CSS.

```css
html {
	box-sizing: border-box;
}

*,
*:before,
*:after {
	box-sizing: inherit;
}
```
